# Generated by Django 4.0.1 on 2022-01-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='photo',
        ),
    ]
