# Generated by Django 4.0.1 on 2022-01-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_review_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
