# Generated by Django 4.0.1 on 2022-01-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='photographer',
        ),
    ]
